---
bibliography: references.bib
---

# 绪论 {.unnumbered}

学习本章节内容，将有助于你对以下问题的理解与思考：

-   什么是发展？发展具有什么特点？
-   什么是发展心理学？它的研究目标和研究任务是什么？
-   发展心理学家需要回答的基本理论问题有哪些？
-   作为一门独立的学科，发展心理学有着怎样的发展历程？
-   发展心理学是如何收集数据的？发展心理学研究是否有其独特的研究设计？
-   为什么要关注发展心理学研究的伦理问题？

::: {.callout-tip appearance="minimal" style="font-family: 'fangsong';"}
古希腊神话中，狮身人面的怪物斯芬克司向路人提出一个谜语：“什么动物早晨用四只脚走路，中午用两只脚走路，晚上用三只脚走路？”路人一旦猜不出谜语，就被斯芬克司吃了。聪明勇敢的俄狄浦斯猜中了答案：人。在生命的早晨，孩子用两条腿和两只手爬行；到了生命的中午，他长大成人，只用两条腿走路；在生命的晚上，他年老体衰，必须借助拐杖走路。其实，斯芬克司的谜语中的早晨、中午、晚上也是人类进化的前期、中期和后期的暗示。所谓“四只脚”，说的是古猿与其他哺乳动物同有四足特征；“两只脚”比喻脱离原始生存状态而直立行走的猿人；被称为“第三只脚”的拐杖实质上是人类文明创造物对人类肢体的延伸。
:::

## 发展心理学概述

在学习发展心理学之初，我们需要弄清楚以下问题：什么是发展？什么是发展心理学？作为心理学重要的一个分支，发展心理学有怎样的研究目标和研究任务？

### 发展和发展心理学的含义

#### 什么是发展

从呱呱落地的那一刻起，人在一生当中都处在不断的发展和变化之中，会经历美好而天真的童年，奔放而阳光的少年，执着而坚忍的青年，忙碌而充实的中年，以及睿智而沉着的老年。从子宫到坟墓，发展贯穿人类的生命全程。那么到底什么是发展？发展心理学中的“发展”和我们日常生活中常说的“发展”具有不同的含义。日常生活中的发展一般是指事物由小到大、由简单到复杂、由低级到高级的变化，而发展心理学中的发展是指从孕育到死亡的生命全程中个体的行为和心理的变化，它具有以下几个特点：

1.  发展是一个持续毕生的过程

    **发展**（development）是个体机能和结构的获得、维持、转换和衰退的过程，这个过程始于精卵结合，终于死亡。生命全程中任何一个时期都可能成为发展的起点或终点。发展并非成年就结束，而是贯穿生命全程。这个过程既包括“得”与“失”，又充满了不平衡。

    首先，发展的过程不是只有“获得”而没有“损失”。任何发展都包含一些方面的增长和一些方面的下降。例如，正规学校教育能够促进儿童认知能力的发展和基础知识的获得，但也可能因为要求儿童遵循规则而限制了他们的创造性。

    其次，发展的过程是不平衡的。各项心理机能系统并非总按照相同的速度发展，而是呈现出多元化的发展趋势。一方面，身体内不同机能系统发展的起始时间、速度以及达到的成熟水平不尽相同，例如，在青春期，个体血管的发育落后于心脏的发育，这就导致了“青春期高血压”现象[@ostchega2009]；另一方面，相同的机能系统在不同阶段和时期的发展速度也不尽相同，例如，在婴儿期，个体的视知觉和听知觉快速发展，而在成年晚期则出现下降趋势。

2.  发展具有可塑性

    **可塑性**（plasticity）指的是个体某种行为发展的可变性。发展的可塑性体现在以下两个方面：

    第一，发展的过程中存在**关键期**（critical period），即在个体早期发展过程中，某一种或某一组反应在某一特定时期或阶段中最容易获得、最容易形成。如果在这个时期或阶段缺少适当的环境刺激，这种或这组反应将不能达到应有水平，甚至永远不会产生。心理发展关键期的研究源于奥地利动物习性学家洛伦兹（K. Z. Lorenz）对动物**印刻**（imprinting）行为的研究。洛伦兹发现，鹅、鸭、雁等鸟类在刚刚孵化出来后的一定时间内，会对自己首先接触到的物体（如人、木马、足球）产生偏好和追随反应，将其当作母亲；如果母亲没有在这个关键时间内出现，它们将对其毫无依恋。研究表明，人类心理发展过程中存在很多关键期。如有人认为儿童在2—5岁是学习口语的关键期[@hoff2001]；4—5岁是幼儿理解他人心理状态的关键期[@liu2008]。

    第二，发展过程中不同能力能够互相代偿，一种能力的损伤或缺失能够被另一种能力代偿。例如，加拿大科学家Meredith等人[-@lomber2010]的研究表明，原本用于处理视觉信息与空间感知的脑区，在个体失明后也能与声音信息形成联结。这就是为什么一些盲人能通过声音来感知空间，实现以耳代目。神经可塑性理论可以解释这种能力代偿：大脑的神经网络能够随着外界环境刺激，不断调整神经之间的联系，因此具有惊人的可塑性和灵活性。

3.  发展具有情境性

    发展是在特定时空中发生的。布朗芬布伦纳（U. Bronfenbrenner, 1917—2005）建立了个体发展的生态系统理论（ecological systems theory），认为人类行为是个体内在因素与外在环境相互作用的结果，如果用函数形式表达就是 $B = f(P, E)$ 。其中，$B$ 代表行为，$P$ 代表个体，$E$ 代表环境。一般心理学家忽视E而轻视P，但布朗芬布伦纳指出，每个人都是“情境中的人”，个体和环境互相作用组成一个整体，个体每时每刻都生活在不同层次的生态系统中。这四层生态系统由里到外分别是：**微观系统**（microsystem），指个体最直接接触到的环境，主要包括家庭、学校、同伴等；**中观系统**（mesosystem），指微观系统和外层系统间起联系作用的环境，如人际关系；**外层系统**（exosystem），指那些个体并未直接参与却对个体有影响的环境，如邻居、大众传媒、法律服务、社区服务等；**宏观系统**（macrosystem），指社会中的价值观、伦理、道德、意识形态等。此外，生态系统中的时间维度被命名为**历时系统**（chronosystem），具体指个体所处的社会历史条件。这些生态系统同时存在，且宏观系统的变化会影响外层系统，进而影响中观系统和微观系统。对个体发展的考察，不应仅停留在微观系统上，而应在各生态系统的相互联系中进行<!--FIXME-->（详细内容参见第一章第四节）。

#### 什么是发展心理学

**发展心理学**（developmental psychology）是心理学的一个分支，具有广义和狭义之分。广义的发展心理学是研究心理发展及其规律的学科，它以系统的眼光来考察生命的变化过程或者动物的进化过程，探讨人的心理如何从原始、低级的状态演化到现代、高级的状态。比较心理学和民族心理学都属于广义的发展心理学范畴：比较心理学主要研究动物心理的演化历程，以描绘动物演化过程中心理发展的总体图景；民族心理学主要研究生活在不同社会历史阶段的各个民族的心理并加以对比，以勾勒人类心理发展的总体轮廓。

通常所说的发展心理学指的是狭义的发展心理学，即个体发展心理学。它探究从胎儿期开始一直到衰老死亡的全过程，个体的能力、情感和社会交往等各方面如何从低级水平向高级水平变化发展。发展心理学尤其注重探究各个年龄阶段的心理特征，关注个体心理从一个年龄阶段发展到另一个年龄阶段的规律，具体包括婴幼儿心理学、儿童心理学、青年心理学、中年心理学和老年心理学。

发展心理学采用科学的方法，对成长、变化和稳定性进行研究。发展心理学家可以采用横向和纵向的视角来考察、研究个体的毕生发展。采用横向视角，发展心理学家将关注人的毕生发展的多个主题，包括**生理发展**（physical development）、**认知发展**（cognitive development）、**人格发展**（personality development）和**社会性发展**（social development）等方面[@feldman2021]。关注生理发展的发展心理学家侧重考察身体构造随年龄发展变化的规律以及影响因素。例如，营养良好对儿童生长速度的影响。关注认知发展的心理学家侧重考察学习、记忆、问题解决和智力等问题。例如，个体如何对生命早期的经历进行回忆，或者智力在不同生命阶段的变化。关注人格发展的心理学家侧重考察生命过程中个体气质与性格的可变性和稳定性等问题。关注社会性发展的心理学家侧重考察个体在生命全程中与他人互动及其社会关系的发展、变化和保持等问题。采用纵向视角，发展心理学家往往关注特定的年龄范畴。如将个体发展过程划分为如下几个年龄阶段：产前期（从受孕到出生）、婴儿期（出生到3岁）、幼儿期（也称学前期，3—6岁）、儿童中期（6—12岁）、少年期（12—20岁）、成年早期（20—40岁）、成年中期（40—60岁）、成年晚期（60岁至生命终止）。这种年龄阶段的划分得到了发展心理学家的广泛接受。同时必须承认，在不同的时代和文化背景下，对年龄阶段的具体划分会有所差异。

### 发展心理学的研究目标和研究任务

发展心理学探讨心理发生和发展的规律，是一门基础学科；同时，发展心理学既服务于教育、医疗、干预等实践领域，具有重要的应用价值。发展心理学的研究目标和研究任务可以归纳为五个方面：

#### 描述心理发展的规律和模式

描述个体心理发展过程中的规律、特点和模式是发展心理学研究最基本的目标和任务，也是一切发展心理学研究的前提。发展心理学家致力于寻找有效的方式来测量个体智力、社会性和人格等方面的变化。例如，研究发现，成人对亲密关系的满意度在20—30岁达到顶峰后开始下降，在40岁时达到低谷后又开始上升，到成年晚期趋于稳定[@bühler2021]。

#### 揭示心理发展的原因和机制

随着年龄的增长，个体的生理、认知、人格和社会性等方面都会发展和变化。那么，这些发展和变化的原因是什么？发展心理学家不仅要解决“是什么”的问题，还要解决“为什么”的问题。研究者在数据和资料的基础上，提出各种假设，通过进一步的观察和实验，验证或构建理论，从而揭示心理发展的原因和机制。例如，很多心理学家对于语言的产生非常好奇，有的研究者认为语言的产生是模仿和强化的结果，而著名心理学家乔姆斯基（A. N. Chomsky, 1928—）提出，人类通过系统遗传获得了一个先天语言获得装置，个体只要将这个先天语言获得装置暴露在恰当的语言环境下使其激活，就能获得语言能力。

#### 测量和解释个体差异

虽然个体在生命全程中会经历相似的发展阶段，其发展变化的模式也是相同的，但不同个体心理发展的速度、所能达到的水平、各种心理过程和行为特点等，并不相同。例如，从能力发展速度上看，有的人早慧，有的人则大器晚成；从能力水平上看，有的人在某方面出众，有的人则表现平庸；从性格特点上看，有的人易挑衅攻击，有的人则合作助人……如何测量和解释这些个体差异也是发展心理学的研究目标和研究任务。

#### 探究不同环境对发展的影响

所有的发展都是在具体的时间和空间中发生的，发展的水平和程度会受到个体所处环境的影响。人们都生活、成长于特定的社会与文化环境中，因此个体的发展过程必然会打上特定社会与文化环境的烙印。例如，研究发现，鄂伦春族生活在大兴安岭和小兴安岭地区，森林被茂密，森林环境和北方寒冷的生态压力使鄂伦春族人养成了较强的独立性和高水平的空间分析能力，从而发展出良好的视空间工作记忆能力[@wang2018]。不同的物质生活和教育条件也使儿童的心理发展水平发生变化，如当前普遍存在的“成熟期提前”现象，就是因为物质生活条件的改善，青少年生理发育普遍提前，相应的心理年龄特征也提前出现。

#### 帮助和指导儿童的发展

我国著名心理学家林崇德指出，发展心理学研究一定要为教育服务。无论是描述心理发展的规律和模式、揭示心理发展的原因和机制，还是测量和解释个体差异、探究不同环境对发展的影响，都是为了更好地服务于个体的成长和发展。首先，发展心理学的研究有助于个体更好地度过每一个发展阶段。例如，传统观念认为母亲在儿童教育中具有绝对作用，研究则表明父亲的教养行为对于儿童认知、语言和气质的发展也有重要的影响[@therole2010]。其次，发展心理学致力于解决个体在发展中遇到的困难或障碍。比如，孤独症是一种普遍性发展障碍，相关领域的发展心理学家就致力于探究孤独症个体的患病原因和改善症状的方法。最后，发展心理学的研究旨在主动塑造和引导个体发展的结果。运用规律来引导个体发展是发展心理学研究的最高目标。主动塑造和引导指的是根据科学理论控制某些变量的决定条件，或创设一定的情境，使研究对象产生理论预期的改变或者发展。例如，学校和家庭可以根据强化理论来增加儿童的亲社会行为，减少其攻击行为。

## 参考文献
