project:
  type: book

book:
  title: "发展心理学（第2版）"
  author: "苏彦捷"
  date: last-modified
  chapters:
    - index.qmd
    - 00.qmd

format:
  html:
    theme: cosmo
    lang: zh

execute:
  freeze: auto
