# 前言 {.unnumbered}

本书第1版交稿时是我系统讲授“发展心理学”课程的第十个年头。巧合的是，当高等教育出版社提出启动本书的修订工作，而我觉得一定要做这件事情的时候，又一个十年过去了。

在这十年里，国家对教材建设和管理的重视程度不断加强，强调教材是落实立德树人根本任务的重要载体，是育人育才的重要依托，并采取了一系列措施，出台了一系列政策文件。习近平总书记高度重视教材建设，多次强调教材是国家事权，并就教材工作发表重要讲话、作出重要指示批示和回信，对推进教材建设提出了一系列重大论断和要求。“加强教材建设和管理”还被写入了党的二十大报告。

在这十年里，我国教育信息化实现跨越式发展，教师信息技术应用能力明显提升，教育信息化应用模式不断创新。随着信息技术的发展，“互联网＋教育”正在构建新的教育教学形态，对教材建设也提出了新的要求。高等教育出版社基于融合出版的理念与要求出版的一系列新形态教材，成为教师教学、学生学习的基本载体和关键支撑，广受师生好评。《发展心理学》的修订也是基于新形态教材理念进行策划的。2019年10月，我主讲的在线开放课程“发展心理学”在中国大学MOOC平台上线，截至2023年3月，正在进行第8次开课，累计学习人数14.6万。在线教学过程中形成的成熟资源已成为修订后的教材的重要内容组成，依托教学平台获得的大量信息也为本书的修订提供了重要支撑。

在修订工作进入尾声时，党的二十大胜利召开。党的二十大报告中明确提出，要“大力发展社会主义先进文化，加强理想信念教育，传承中华文明，促进物的全面丰富和人的全面发展”。发展心理学关注的人的全面发展不仅包括基于横向视角的人的生理发展、认知发展、人格发展和社会性发展，还包括基于纵向视角的人的毕生发展。关注人的全面发展，建立健全多形式衔接、多通道成长、可持续发展的教育和培训体系，让不同禀赋和需要的学生能够多样化成才，这对建设全民终身学习的学习型社会、学习型大国有重要作用。为了贯彻落实党的二十大精神进教材，我们在深入学习党的二十大报告的基础上，对书稿再次进行了全面梳理和完善。

发展心理学教材通常有两种编排方式：一种是按照年龄阶段编排，另一种是按照主题编排。就本书到底采用哪种编排方式，我们经过多次研讨，最终决定采用主题编排方式。但作为毕生发展心理学，年龄是永恒的线索，建议读者阅读各主题的内容时，参考一些以年龄为线索的教材，经纬相间不断交错才会编织出完整的发展心理学图景。

本书在内容的选择与更新方面，重点考虑了以下几个方面：一是希望重现知识的产生、发展和嬗变过程，如介绍重要代表人物的研究生涯，重要成果的研究过程，等等，希望学生不仅知道研究结论，而且了解研究渊源，以便更好地理解相关知识。二是关注知识的传承与创新发展。对于教材的主体内容，我们选取了争议不大、在学术界已有定论的思想体系，具有相对的成熟性并遵守该学科的学术规范。对那些在学术界还存有争议的学术观点，我们也适当地收录，主要通过“专栏”“知识窗”来体现，以引发学生的思考和讨论。三是体现本土化研究进展，特别注意介绍我国学者取得的研究成果。四是与时俱进，充分反映各个主题研究的新进展，更新相关的政策、法规等内容，并根据学科发展和学生受众的时代变化更换、调整了部分案例。

本书在体例的编排与设计方面，重点考虑了以下几个方面：一是在编写过程中非常注意参考文献的真实引用和完整引用，希望通过本书让学生认识到，心理学研究和实践工作，要有根有据。二是充分考虑学生的理解能力和接受能力，本书写作力争做到语言通俗生动、案例丰富、资料详实、可读性强。三是为了适应信息技术时代的教学需求，我们用二维码关联了“发展心理学”课程的相关“微课”、阅读材料，旨在进一步引起学生思考、拓宽学习视野。

在很多场合，我都会阐述发展共同体或心理健康共同体的理念：无论是教书育人还是养育后代，做教师的、做家长的与学生、子女都是一个共同体，只有共同体发展、成长得好，才会有资源支持我们将教学和养育工作完成得好。在《发展心理学》教材的编写和修订过程中，编写者也在成长。第1版编写时，我和两位副主编的学术背景正好代表三个有发展心理学教学和研究传统的心理学高等教育机构：我毕业于北京大学，在北京大学工作；张丽锦教授毕业于中国科学院心理研究所，当时在宁夏大学工作；王美芳教授毕业于北京师范大学，当时在山东师范大学工作。我们都从事发展心理学的教学和研究工作，也希望本书不仅能传承三个机构发展心理学的传统，而且通过这种交叉体现一定的多样性，赋予这个学科更强的生命力。这十年来，我虽然还在北京大学工作，但北京大学的心理学系已经变成了心理与认知科学学院，王美芳教授去了首都师范大学工作，张丽锦教授去了陕西师范大学工作，其他编写者或者从当时的学生变成了心理学教师、心理学科研工作者，或者从青涩的年轻教师成长为成熟教师、骨干教师。我们共同的变化是经过了十年的历练，比以前有了更多的教学和研究经验，希望读者也能感受到我们的这种发展和成熟。理解类似的发展过程是发展心理学这一学科特有的魅力所在，不仅有学术之递，还有生活之术。

本书是集体努力的结果。这次修订工作由我和王美芳教授、张丽锦教授三人一起组织，10余位编写者——他们大都参与了第1版的编写工作——合作完成，各章分工情况如下：

| 章节 | 统稿负责人 | 第2版编写人员及工作单位 | 第1版编写人员 |
| ------------ | ---------- | ---------------- | ---------------- |
| 绪论 | 苏彦捷 | 刘艳春（湖北师范大学） | 黄鬻青、刘艳春 |  |
| 发展心理学的重要理论 | 张丽锦 | 张晨（宁夏大学） | 张晨、田江 |
| 发展的生物学基础 | 苏彦捷 | 廖宗卿（四川师范大学） | 廖宗卿、王玥 |
| 认知发展 | 苏彦捷 | 陈雨露（北京联合大学） | 陈雨露、王斯、古丽努尔·阿扎提 |
| 语言发展 | 苏彦捷 | 孟祥芝（北京大学） | 孟祥芝 |
| 智力发展 | 张丽锦 | 梁渊（西安外国语大学） | 邱桂平 |
| 情绪、气质与人格发展 | 王美芳 | 王树青（济南大学） | 王树青 |
| 自我与社会认知 | 张丽锦 | 范莉莎（陕西师范大学） | 赵明旭 |
| 性别差异与性别角色的社会化 | 王美芳 | 张庆（山东青年政治学院） | 张庆 |
| 社会交往的发展 | 张丽锦 | 辛莫野（陕西师范大学） | 张晨、曾祥岚 |
| 家庭发展 | 王美芳 | 王美芳（首都师范大学） | 王美芳 |
| 发展的环境因素 | 王美芳 | 赵景欣（山东师范大学） | 赵景欣 |

本书第1版自出版以来，被众多院校选作“发展心理学”课程教材，得到了广泛认可，我们期望第2版也能得到认可，继续出现在大家的课堂和书桌上。在编写和修订过程中，我们参阅和引用了许多研究成果，在此一并表示感谢！虽然几经修改，但书中可能还会有一些疏漏或有待完善之处，恳请广大读者批评指正。

::: {style="text-align: right;"}
苏彦捷<br />2023年3月
:::
